"""add device_info to audit_logs

Revision ID: b8484e05b8f9
Revises: 6755380a429d
Create Date: 2026-02-16 14:45:46.237625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8484e05b8f9'
down_revision: Union[str, None] = '6755380a429d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_token_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_staff_profiles_staff_type'), table_name='staff_profiles')
    op.drop_table('staff_profiles')
    op.add_column('addresses', sa.Column('address_line1', sa.String(), nullable=False))
    op.add_column('addresses', sa.Column('address_line2', sa.String(), nullable=True))
    op.alter_column('addresses', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('audit_logs', sa.Column('device_info', sa.String(), nullable=True))
    op.create_index(op.f('ix_kyc_documents_user_id'), 'kyc_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kyc_documents_user_id'), table_name='kyc_documents')
    op.drop_column('audit_logs', 'device_info')
    op.alter_column('addresses', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('addresses', 'address_line2')
    op.drop_column('addresses', 'address_line1')
    op.create_table('staff_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dealer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('staff_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reporting_manager_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer_profiles.id'], name=op.f('staff_profiles_dealer_id_fkey')),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['users.id'], name=op.f('staff_profiles_reporting_manager_id_fkey')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('staff_profiles_station_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('staff_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('staff_profiles_pkey')),
    sa.UniqueConstraint('employment_id', name=op.f('staff_profiles_employment_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name=op.f('staff_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_staff_profiles_staff_type'), 'staff_profiles', ['staff_type'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_active_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_sessions_pkey'))
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_id'), 'user_sessions', ['token_id'], unique=False)
    # ### end Alembic commands ###
