info:
  name: List Notification Configs
  type: http
  seq: 191
  tags:
    - Admin_Core
    - Admin_Notifications

http:
  method: GET
  url: "{{baseUrl}}/api/v1/admin/notifications/config"
  auth:
    type: oauth2
    flow: resource_owner_password_credentials
    accessTokenUrl: /api/v1/auth/token
    refreshTokenUrl: "{{oauth_refresh_url}}"
    credentials:
      clientId: "{{oauth_client_id}}"
      clientSecret: "{{oauth_client_secret}}"
      placement: header
    tokenConfig:
      placement:
        header: Bearer
      source: access_token
    settings:
      autoFetchToken: false
      autoRefreshToken: true

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: Successful Response
    request:
      url: "{{baseUrl}}/api/v1/admin/notifications/config"
      method: GET
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          [
            {
              "id": 0,
              "provider": "",
              "channel": "",
              "display_name": "",
              "api_key": "",
              "sender_id": "",
              "is_active": false,
              "last_tested_at": "",
              "test_status": "",
              "created_at": "",
              "updated_at": ""
            }
          ]
