"""add device info and token hash to user session

Revision ID: 2c5038fb67d6
Revises: a1b2c3d4e5f6
Create Date: 2026-02-18 12:02:26.819954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5038fb67d6'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('device_id', sa.String(), nullable=True))
    op.add_column('user_sessions', sa.Column('device_name', sa.String(), nullable=True))
    op.add_column('user_sessions', sa.Column('refresh_token_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_sessions_device_id'), 'user_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_device_id'), table_name='user_sessions')
    op.drop_column('user_sessions', 'refresh_token_hash')
    op.drop_column('user_sessions', 'device_name')
    op.drop_column('user_sessions', 'device_id')
    # ### end Alembic commands ###
