"""add_logistics_models

Revision ID: 4b027b1f6093
Revises: ade992443985
Create Date: 2026-02-04 15:41:47.672172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b027b1f6093'
down_revision: Union[str, None] = 'ade992443985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vehicle_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vehicle_plate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('last_location_update', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_deliveries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('delivery_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('return_request_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pickup_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('proof_of_delivery_img', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_signature', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('otp_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['ecommerce_orders.id'], ),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('delivery_routes', sa.Column('driver_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'delivery_routes', 'driver_profiles', ['driver_id'], ['id'])
    op.add_column('route_stops', sa.Column('delivery_assignment_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'route_stops', 'delivery_assignments', ['delivery_assignment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route_stops', type_='foreignkey')
    op.drop_column('route_stops', 'delivery_assignment_id')
    op.drop_constraint(None, 'delivery_routes', type_='foreignkey')
    op.drop_column('delivery_routes', 'driver_id')
    op.drop_table('delivery_assignments')
    op.drop_table('driver_profiles')
    # ### end Alembic commands ###
