"""Add last_global_logout_at to User model

Revision ID: 4cd75111728e
Revises: 50d2ce886b6a
Create Date: 2026-02-05 13:33:59.415186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cd75111728e'
down_revision: Union[str, None] = '50d2ce886b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS ix_staff_profiles_staff_type')
    op.execute('DROP TABLE IF EXISTS staff_profiles')
    op.add_column('stations', sa.Column('dealer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stations', 'dealer_profiles', ['dealer_id'], ['id'])
    op.add_column('users', sa.Column('last_global_logout_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_global_logout_at')
    op.drop_constraint(None, 'stations', type_='foreignkey')
    op.drop_column('stations', 'dealer_id')
    op.create_table('staff_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dealer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('staff_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reporting_manager_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer_profiles.id'], name='staff_profiles_dealer_id_fkey'),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['users.id'], name='staff_profiles_reporting_manager_id_fkey'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name='staff_profiles_station_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='staff_profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='staff_profiles_pkey'),
    sa.UniqueConstraint('employment_id', name='staff_profiles_employment_id_key'),
    sa.UniqueConstraint('user_id', name='staff_profiles_user_id_key')
    )
    op.create_index('ix_staff_profiles_staff_type', 'staff_profiles', ['staff_type'], unique=False)
    # ### end Alembic commands ###
