"""add_dealer_features

Revision ID: 50d2ce886b6a
Revises: 77f44e2f3bd0
Create Date: 2026-02-04 18:26:36.597706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d2ce886b6a'
down_revision: Union[str, None] = '77f44e2f3bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
