"""Add thorough maintenance schedules

Revision ID: 53bfe56946c5
Revises: d3b456bb673a
Create Date: 2026-03-26 15:52:56.713705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '53bfe56946c5'
down_revision: Union[str, None] = 'd3b456bb673a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('station_type', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('maintenance_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('checklist', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_table('indents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('manager_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.dealer_profiles.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['logistics.warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_indents_dealer_id'), 'indents', ['dealer_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_indents_warehouse_id'), 'indents', ['warehouse_id'], unique=False, schema='inventory')
    op.create_table('grns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indent_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.dealer_profiles.id'], ),
    sa.ForeignKeyConstraint(['indent_id'], ['inventory.indents.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['core.users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['logistics.warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_grns_indent_id'), 'grns', ['indent_id'], unique=False, schema='inventory')
    op.create_table('indent_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indent_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('approved_quantity', sa.Integer(), nullable=False),
    sa.Column('dispatched_quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['indent_id'], ['inventory.indents.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.battery_catalog.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_indent_items_indent_id'), 'indent_items', ['indent_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_indent_items_product_id'), 'indent_items', ['product_id'], unique=False, schema='inventory')
    op.create_table('grn_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('indent_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.Column('damaged_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grn_id'], ['inventory.grns.id'], ),
    sa.ForeignKeyConstraint(['indent_item_id'], ['inventory.indent_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.battery_catalog.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_grn_items_grn_id'), 'grn_items', ['grn_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_grn_items_indent_item_id'), 'grn_items', ['indent_item_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_grn_items_product_id'), 'grn_items', ['product_id'], unique=False, schema='inventory')
    op.create_table('battery_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battery_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('field_changed', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['battery_id'], ['inventory.batteries.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_battery_audit_logs_battery_id'), 'battery_audit_logs', ['battery_id'], unique=False, schema='inventory')
    op.create_table('battery_health_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battery_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('health_percentage', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['battery_id'], ['inventory.batteries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_battery_health_history_battery_id'), 'battery_health_history', ['battery_id'], unique=False, schema='inventory')

    op.add_column('dealer_inventories', sa.Column('product_id', sa.Integer(), nullable=False), schema='dealers')
    op.alter_column('dealer_inventories', 'battery_model',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='dealers')
    op.create_index(op.f('ix_dealers_dealer_inventories_product_id'), 'dealer_inventories', ['product_id'], unique=False, schema='dealers')
    op.create_foreign_key(None, 'dealer_inventories', 'battery_catalog', ['product_id'], ['id'], source_schema='dealers', referent_schema='inventory')
    op.alter_column('batteryhealthlog', 'battery_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='inventory')
    op.add_column('maintenance_records', sa.Column('schedule_id', sa.String(), nullable=True), schema='inventory')
    op.add_column('maintenance_records', sa.Column('station_id', sa.Integer(), nullable=True), schema='inventory')
    op.add_column('maintenance_records', sa.Column('template_id', sa.String(), nullable=True), schema='inventory')
    op.add_column('maintenance_records', sa.Column('checklist_submission', sa.String(), nullable=True), schema='inventory')
    op.add_column('maintenance_records', sa.Column('checklist_result', sa.String(), nullable=True), schema='inventory')
    op.add_column('maintenance_records', sa.Column('notes', sa.String(), nullable=True), schema='inventory')
    op.add_column('maintenance_records', sa.Column('started_at', sa.DateTime(), nullable=True), schema='inventory')
    op.add_column('maintenance_records', sa.Column('completed_at', sa.DateTime(), nullable=True), schema='inventory')
    op.alter_column('maintenance_records', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('inventory.maintenance_records_id_seq'::regclass)"),
               schema='inventory')
    op.alter_column('maintenance_records', 'entity_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='inventory')
    op.alter_column('maintenance_records', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='inventory')
    op.alter_column('maintenance_records', 'maintenance_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='inventory')
    op.alter_column('maintenance_records', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='inventory')
    op.add_column('maintenance_schedules', sa.Column('station_id', sa.Integer(), nullable=True), schema='inventory')
    op.add_column('maintenance_schedules', sa.Column('title', sa.String(), nullable=True), schema='inventory')
    op.add_column('maintenance_schedules', sa.Column('description', sa.String(), nullable=True), schema='inventory')
    op.add_column('maintenance_schedules', sa.Column('start_time', sa.DateTime(), nullable=True), schema='inventory')
    op.add_column('maintenance_schedules', sa.Column('end_time', sa.DateTime(), nullable=True), schema='inventory')
    op.add_column('maintenance_schedules', sa.Column('duration_minutes', sa.Integer(), nullable=True), schema='inventory')
    op.add_column('maintenance_schedules', sa.Column('maintenance_type', sa.String(), nullable=True), schema='inventory')
    op.add_column('maintenance_schedules', sa.Column('status', sa.String(), nullable=False), schema='inventory')
    op.add_column('maintenance_schedules', sa.Column('recurrence_rule', sa.String(), nullable=True), schema='inventory')
    op.add_column('maintenance_schedules', sa.Column('assigned_to', sa.Integer(), nullable=True), schema='inventory')
    op.add_column('maintenance_schedules', sa.Column('updated_at', sa.DateTime(), nullable=True), schema='inventory')
    op.alter_column('maintenance_schedules', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('inventory.maintenance_schedules_id_seq'::regclass)"),
               schema='inventory')
    op.alter_column('maintenance_schedules', 'entity_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='inventory')
    op.alter_column('maintenance_schedules', 'checklist',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='inventory')
    op.create_foreign_key(None, 'maintenance_records', 'maintenance_schedules', ['schedule_id'], ['id'], source_schema='inventory', referent_schema='inventory')
    op.create_foreign_key(None, 'maintenance_records', 'maintenance_templates', ['template_id'], ['id'], source_schema='inventory', referent_schema='inventory')
    op.alter_column('purchases', 'battery_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='rentals')
    op.alter_column('charging_queue', 'battery_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='stations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charging_queue', 'battery_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='stations')
    op.alter_column('purchases', 'battery_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='rentals')
    op.drop_constraint('maintenance_records_schedule_id_fkey', 'maintenance_records', schema='inventory', type_='foreignkey')
    op.drop_constraint('maintenance_records_template_id_fkey', 'maintenance_records', schema='inventory', type_='foreignkey')
    op.alter_column('maintenance_schedules', 'checklist',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='inventory')
    op.alter_column('maintenance_schedules', 'entity_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='inventory')
    op.alter_column('maintenance_schedules', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('inventory.maintenance_schedules_id_seq'::regclass)"),
               schema='inventory')
    op.drop_column('maintenance_schedules', 'updated_at', schema='inventory')
    op.drop_column('maintenance_schedules', 'assigned_to', schema='inventory')
    op.drop_column('maintenance_schedules', 'recurrence_rule', schema='inventory')
    op.drop_column('maintenance_schedules', 'status', schema='inventory')
    op.drop_column('maintenance_schedules', 'maintenance_type', schema='inventory')
    op.drop_column('maintenance_schedules', 'duration_minutes', schema='inventory')
    op.drop_column('maintenance_schedules', 'end_time', schema='inventory')
    op.drop_column('maintenance_schedules', 'start_time', schema='inventory')
    op.drop_column('maintenance_schedules', 'description', schema='inventory')
    op.drop_column('maintenance_schedules', 'title', schema='inventory')
    op.drop_column('maintenance_schedules', 'station_id', schema='inventory')
    op.alter_column('maintenance_records', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='inventory')
    op.alter_column('maintenance_records', 'maintenance_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='inventory')
    op.alter_column('maintenance_records', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='inventory')
    op.alter_column('maintenance_records', 'entity_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='inventory')
    op.alter_column('maintenance_records', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('inventory.maintenance_records_id_seq'::regclass)"),
               schema='inventory')
    op.drop_column('maintenance_records', 'completed_at', schema='inventory')
    op.drop_column('maintenance_records', 'started_at', schema='inventory')
    op.drop_column('maintenance_records', 'notes', schema='inventory')
    op.drop_column('maintenance_records', 'checklist_result', schema='inventory')
    op.drop_column('maintenance_records', 'checklist_submission', schema='inventory')
    op.drop_column('maintenance_records', 'template_id', schema='inventory')
    op.drop_column('maintenance_records', 'station_id', schema='inventory')
    op.drop_column('maintenance_records', 'schedule_id', schema='inventory')
    op.alter_column('batteryhealthlog', 'battery_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='inventory')
    op.drop_constraint(None, 'dealer_inventories', schema='dealers', type_='foreignkey')
    op.drop_index(op.f('ix_dealers_dealer_inventories_product_id'), table_name='dealer_inventories', schema='dealers')
    op.alter_column('dealer_inventories', 'battery_model',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='dealers')
    op.drop_column('dealer_inventories', 'product_id', schema='dealers')

    op.drop_index(op.f('ix_inventory_battery_health_history_battery_id'), table_name='battery_health_history', schema='inventory')
    op.drop_table('battery_health_history', schema='inventory')
    op.drop_index(op.f('ix_inventory_battery_audit_logs_battery_id'), table_name='battery_audit_logs', schema='inventory')
    op.drop_table('battery_audit_logs', schema='inventory')
    op.drop_index(op.f('ix_inventory_grn_items_product_id'), table_name='grn_items', schema='inventory')
    op.drop_index(op.f('ix_inventory_grn_items_indent_item_id'), table_name='grn_items', schema='inventory')
    op.drop_index(op.f('ix_inventory_grn_items_grn_id'), table_name='grn_items', schema='inventory')
    op.drop_table('grn_items', schema='inventory')
    op.drop_index(op.f('ix_inventory_indent_items_product_id'), table_name='indent_items', schema='inventory')
    op.drop_index(op.f('ix_inventory_indent_items_indent_id'), table_name='indent_items', schema='inventory')
    op.drop_table('indent_items', schema='inventory')
    op.drop_index(op.f('ix_inventory_grns_indent_id'), table_name='grns', schema='inventory')
    op.drop_table('grns', schema='inventory')
    op.drop_index(op.f('ix_inventory_indents_warehouse_id'), table_name='indents', schema='inventory')
    op.drop_index(op.f('ix_inventory_indents_dealer_id'), table_name='indents', schema='inventory')
    op.drop_table('indents', schema='inventory')
    op.drop_table('maintenance_templates', schema='inventory')
    # ### end Alembic commands ###
