"""Add battery discovery and rental tables

Revision ID: 63e31f07d91a
Revises: ef3c2dc85e46
Create Date: 2026-02-15 22:46:43.500002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '63e31f07d91a'
down_revision: Union[str, None] = 'ef3c2dc85e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batteries', sa.Column('qr_code_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('batteries', sa.Column('battery_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('batteries', sa.Column('capacity_mah', sa.Integer(), nullable=False))
    op.add_column('batteries', sa.Column('voltage_v', sa.Float(), nullable=False))
    op.add_column('batteries', sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('batteries', sa.Column('model_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('batteries', sa.Column('rental_price_per_day', sa.Float(), nullable=False))
    op.add_column('batteries', sa.Column('damage_deposit_amount', sa.Float(), nullable=False))
    op.add_column('batteries', sa.Column('certification_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_batteries_qr_code_data'), 'batteries', ['qr_code_data'], unique=True)
    op.add_column('promo_codes', sa.Column('min_rental_days', sa.Integer(), nullable=False))
    op.add_column('rentals', sa.Column('rental_duration_days', sa.Integer(), nullable=False))
    op.add_column('rentals', sa.Column('daily_rate', sa.Float(), nullable=False))
    op.add_column('rentals', sa.Column('damage_deposit', sa.Float(), nullable=False))
    op.add_column('rentals', sa.Column('discount_amount', sa.Float(), nullable=False))
    op.add_column('rentals', sa.Column('promo_code_id', sa.Integer(), nullable=True))
    op.add_column('rentals', sa.Column('late_fee_amount', sa.Float(), nullable=False))
    op.add_column('rentals', sa.Column('late_fee_applicable', sa.Boolean(), nullable=False))
    op.add_column('rentals', sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
    op.add_column('rentals', sa.Column('pickup_verified', sa.Boolean(), nullable=False))
    op.add_column('rentals', sa.Column('return_verified', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'rentals', 'promo_codes', ['promo_code_id'], ['id'])
    op.add_column('reviews', sa.Column('rental_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('response_from_station', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('reviews', sa.Column('is_verified_rental', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('helpful_count', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'rentals', ['rental_id'], ['id'])
    op.add_column('stations', sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stations', sa.Column('opening_time', sa.DateTime(), nullable=True))
    op.add_column('stations', sa.Column('closing_time', sa.DateTime(), nullable=True))
    op.add_column('stations', sa.Column('is_24x7', sa.Boolean(), nullable=False))
    op.add_column('stations', sa.Column('amenities', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'amenities')
    op.drop_column('stations', 'is_24x7')
    op.drop_column('stations', 'closing_time')
    op.drop_column('stations', 'opening_time')
    op.drop_column('stations', 'contact_email')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'helpful_count')
    op.drop_column('reviews', 'is_verified_rental')
    op.drop_column('reviews', 'response_from_station')
    op.drop_column('reviews', 'rental_id')
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.drop_column('rentals', 'return_verified')
    op.drop_column('rentals', 'pickup_verified')
    op.drop_column('rentals', 'terms_accepted_at')
    op.drop_column('rentals', 'late_fee_applicable')
    op.drop_column('rentals', 'late_fee_amount')
    op.drop_column('rentals', 'promo_code_id')
    op.drop_column('rentals', 'discount_amount')
    op.drop_column('rentals', 'damage_deposit')
    op.drop_column('rentals', 'daily_rate')
    op.drop_column('rentals', 'rental_duration_days')
    op.drop_column('promo_codes', 'min_rental_days')
    op.drop_index(op.f('ix_batteries_qr_code_data'), table_name='batteries')
    op.drop_column('batteries', 'certification_details')
    op.drop_column('batteries', 'damage_deposit_amount')
    op.drop_column('batteries', 'rental_price_per_day')
    op.drop_column('batteries', 'model_number')
    op.drop_column('batteries', 'manufacturer')
    op.drop_column('batteries', 'voltage_v')
    op.drop_column('batteries', 'capacity_mah')
    op.drop_column('batteries', 'battery_type')
    op.drop_column('batteries', 'qr_code_data')
    # ### end Alembic commands ###
