"""dealer_notificaiton_pre

Revision ID: 77ede8d4ea8c
Revises: ff5a7d699e68
Create Date: 2026-03-24 15:07:21.847981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77ede8d4ea8c'
down_revision: Union[str, None] = 'ff5a7d699e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_notification_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('low_inventory_alert', sa.Boolean(), nullable=False),
    sa.Column('low_inventory_threshold', sa.Integer(), nullable=False),
    sa.Column('maintenance_due_alert', sa.Boolean(), nullable=False),
    sa.Column('maintenance_reminder_days', sa.Integer(), nullable=False),
    sa.Column('new_booking_alert', sa.Boolean(), nullable=False),
    sa.Column('support_ticket_alert', sa.Boolean(), nullable=False),
    sa.Column('daily_summary_email', sa.Boolean(), nullable=False),
    sa.Column('weekly_report_email', sa.Boolean(), nullable=False),
    sa.Column('sms_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dealer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dealer_notification_prefs')
    # ### end Alembic commands ###
