"""add_missing_columns

Revision ID: 7ca261ec12f5
Revises: a1b2c3d4e5f6
Create Date: 2026-04-14 00:01:54.562877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ca261ec12f5'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_stock_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='stockrequestpriority'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'FULFILLED', 'CANCELLED', name='stockrequeststatus'), nullable=False),
    sa.Column('admin_notes', sa.String(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_reason', sa.String(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_quantity', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer_profiles.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['battery_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_stock_requests_dealer_id'), 'dealer_stock_requests', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_dealer_stock_requests_status'), 'dealer_stock_requests', ['status'], unique=False)
    op.add_column('dealer_profiles', sa.Column('global_rental_settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dealer_profiles', 'global_rental_settings')
    op.drop_index(op.f('ix_dealer_stock_requests_status'), table_name='dealer_stock_requests')
    op.drop_index(op.f('ix_dealer_stock_requests_dealer_id'), table_name='dealer_stock_requests')
    op.drop_table('dealer_stock_requests')
    # ### end Alembic commands ###
