"""add_commission_models

Revision ID: 861e43cb106d
Revises: 3b84e9b78f7b
Create Date: 2026-02-04 16:46:07.165476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '861e43cb106d'
down_revision: Union[str, None] = '3b84e9b78f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('flat_fee', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_configs_transaction_type'), 'commission_configs', ['transaction_type'], unique=False)
    op.create_table('commission_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('commissions')
    op.drop_table('dealer_settlements')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_settlements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dealer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('total_commission', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_deductions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('net_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pdf_statement_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer_profiles.id'], name='dealer_settlements_dealer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dealer_settlements_pkey')
    )
    op.create_table('commissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dealer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('settlement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer_profiles.id'], name='commissions_dealer_id_fkey'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], name='commissions_settlement_id_fkey'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='commissions_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='commissions_pkey')
    )
    op.drop_table('commission_logs')
    op.drop_index(op.f('ix_commission_configs_transaction_type'), table_name='commission_configs')
    op.drop_table('commission_configs')
    # ### end Alembic commands ###
