"""create user invite model

Revision ID: 935e9af859f4
Revises: 87d9afed47a0
Create Date: 2026-03-25 15:21:16.382856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935e9af859f4'
down_revision: Union[str, None] = '87d9afed47a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('invited_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitestatus'), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_invites_email'), 'user_invites', ['email'], unique=False)
    op.create_index(op.f('ix_user_invites_invited_by'), 'user_invites', ['invited_by'], unique=False)
    op.create_index(op.f('ix_user_invites_status'), 'user_invites', ['status'], unique=False)
    op.create_index(op.f('ix_user_invites_token'), 'user_invites', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_invites_token'), table_name='user_invites')
    op.drop_index(op.f('ix_user_invites_status'), table_name='user_invites')
    op.drop_index(op.f('ix_user_invites_invited_by'), table_name='user_invites')
    op.drop_index(op.f('ix_user_invites_email'), table_name='user_invites')
    op.drop_table('user_invites')
    # ### end Alembic commands ###
