"""sync_db_schema_v2

Revision ID: ade992443985
Revises: 977e543b1c75
Create Date: 2026-02-04 15:34:37.973874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ade992443985'
down_revision: Union[str, None] = '977e543b1c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('delivery_routes_driver_id_fkey', 'delivery_routes', type_='foreignkey')
    op.drop_column('delivery_routes', 'driver_id')
    op.drop_constraint('route_stops_delivery_assignment_id_fkey', 'route_stops', type_='foreignkey')
    op.drop_column('route_stops', 'delivery_assignment_id')
    op.create_table('battery_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('capacity_ah', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('dimensions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cycle_life_expectancy', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battery_specs_name'), 'battery_specs', ['name'], unique=True)
    op.create_table('continents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_continents_name'), 'continents', ['name'], unique=True)
    op.create_table('battery_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_date', sa.DateTime(), nullable=False),
    sa.Column('purchase_order_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spec_id'], ['battery_specs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battery_batches_batch_number'), 'battery_batches', ['batch_number'], unique=True)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('continent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['continent_id'], ['continents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('compatible_battery_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=False)
    op.create_table('dealer_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('total_commission', sa.Float(), nullable=False),
    sa.Column('total_deductions', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_statement_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_internal_note', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battery_lifecycle_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battery_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['battery_id'], ['batteries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battery_lifecycle_events_event_type'), 'battery_lifecycle_events', ['event_type'], unique=False)
    op.create_table('battery_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battery_id', sa.Integer(), nullable=False),
    sa.Column('from_location_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['battery_id'], ['batteries.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_table('telemetics_data',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('battery_id', sa.Integer(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('current', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('soc', sa.Float(), nullable=False),
    sa.Column('soh', sa.Float(), nullable=False),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('gps_altitude', sa.Float(), nullable=True),
    sa.Column('gps_speed', sa.Float(), nullable=True),
    sa.Column('error_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['battery_id'], ['batteries.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'battery_id')
    )
    op.create_index(op.f('ix_telemetics_data_battery_id'), 'telemetics_data', ['battery_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_name'), 'zones', ['name'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('license_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('contract_start_date', sa.DateTime(), nullable=True),
    sa.Column('contract_end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gps_coordinates', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_email'), 'vendors', ['email'], unique=True)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_table('vendor_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_documents_document_type'), 'vendor_documents', ['document_type'], unique=False)
    op.create_table('station_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('battery_id', sa.Integer(), nullable=True),
    sa.Column('current_power_w', sa.Float(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['battery_id'], ['batteries.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swap_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('old_battery_id', sa.Integer(), nullable=True),
    sa.Column('old_battery_soc', sa.Float(), nullable=True),
    sa.Column('return_slot_id', sa.Integer(), nullable=True),
    sa.Column('new_battery_id', sa.Integer(), nullable=True),
    sa.Column('new_battery_soc', sa.Float(), nullable=True),
    sa.Column('dispense_slot_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['new_battery_id'], ['batteries.id'], ),
    sa.ForeignKeyConstraint(['old_battery_id'], ['batteries.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pricingrecommendation')
    op.drop_table('auto_responses')
    op.drop_index('ix_adminuser_email', table_name='adminuser')
    op.drop_table('adminuser')
    op.drop_table('swap_histories')
    op.drop_table('delivery_assignments')
    op.drop_table('swap_requests')
    op.drop_table('driver_profiles')
    op.drop_index('ix_faq_items_category_id', table_name='faq_items')
    op.drop_index('ix_faq_items_question', table_name='faq_items')
    op.drop_table('faq_items')
    op.drop_table('faq_categories')
    op.drop_index('ix_demandforecast_forecast_date', table_name='demandforecast')
    op.drop_table('demandforecast')
    op.drop_table('slots')
    op.drop_index('ix_chat_messages_session_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_timestamp', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_chat_sessions_started_at', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_status', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_user_id', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('ix_churnprediction_user_id', table_name='churnprediction')
    op.drop_table('churnprediction')
    op.add_column('batteries', sa.Column('spec_id', sa.Integer(), nullable=True))
    op.add_column('batteries', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.add_column('batteries', sa.Column('retirement_date', sa.DateTime(), nullable=True))
    op.add_column('batteries', sa.Column('location_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('batteries', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('batteries', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'batteries', 'battery_specs', ['spec_id'], ['id'])
    op.create_foreign_key(None, 'batteries', 'battery_batches', ['batch_id'], ['id'])
    op.drop_column('batteries', 'model')
    op.drop_column('batteries', 'capacity_ah')
    op.drop_column('batteries', 'last_swap_at')
    op.drop_column('batteries', 'voltage')
    op.drop_column('batteries', 'temperature')

    op.add_column('settlements', sa.Column('vendor_id', sa.Integer(), nullable=False))
    op.add_column('settlements', sa.Column('total_revenue', sa.Float(), nullable=False))
    op.add_column('settlements', sa.Column('platform_fee', sa.Float(), nullable=False))
    op.add_column('settlements', sa.Column('tax_amount', sa.Float(), nullable=False))
    op.add_column('settlements', sa.Column('payable_amount', sa.Float(), nullable=False))
    op.add_column('settlements', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('settlements', sa.Column('transaction_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('settlements', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_constraint('settlements_dealer_id_fkey', 'settlements', type_='foreignkey')
    op.create_foreign_key(None, 'settlements', 'vendors', ['vendor_id'], ['id'])
    op.drop_column('settlements', 'dealer_id')
    op.drop_column('settlements', 'generated_at')
    op.drop_column('settlements', 'net_amount')
    op.drop_column('settlements', 'total_deductions')
    op.drop_column('settlements', 'total_commission')
    op.drop_column('settlements', 'pdf_statement_url')
    op.add_column('stations', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.add_column('stations', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.add_column('stations', sa.Column('station_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('stations', sa.Column('power_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('stations', sa.Column('connectivity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('stations', sa.Column('firmware_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stations', sa.Column('total_slots', sa.Integer(), nullable=False))
    op.drop_constraint('stations_dealer_id_fkey', 'stations', type_='foreignkey')
    op.create_foreign_key(None, 'stations', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'stations', 'zones', ['zone_id'], ['id'])
    op.drop_column('stations', 'dealer_id')
    op.add_column('support_tickets', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.drop_index('ix_support_tickets_created_at', table_name='support_tickets')
    op.drop_index('ix_support_tickets_status', table_name='support_tickets')
    op.drop_index('ix_support_tickets_ticket_number', table_name='support_tickets')
    op.drop_index('ix_support_tickets_user_id', table_name='support_tickets')
    op.create_index(op.f('ix_support_tickets_category'), 'support_tickets', ['category'], unique=False)
    op.drop_constraint('support_tickets_assigned_agent_id_fkey', 'support_tickets', type_='foreignkey')
    op.drop_column('support_tickets', 'closed_at')
    op.drop_column('support_tickets', 'assigned_agent_id')
    op.drop_column('support_tickets', 'is_overdue')
    op.drop_column('support_tickets', 'resolution_notes')
    op.drop_column('support_tickets', 'sla_due_at')
    op.drop_column('support_tickets', 'ticket_number')
    op.drop_column('support_tickets', 'customer_satisfaction')
    op.drop_column('support_tickets', 'description')
    op.drop_column('support_tickets', 'resolved_at')
    op.add_column('transactions', sa.Column('balance_after', sa.Float(), nullable=False))
    op.add_column('transactions', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('transactions', sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('transactions', sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.drop_column('transactions', 'razorpay_order_id')
    op.add_column('wallets', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'currency')
    op.add_column('transactions', sa.Column('razorpay_order_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_column('transactions', 'reference_id')
    op.drop_column('transactions', 'reference_type')
    op.drop_column('transactions', 'category')
    op.drop_column('transactions', 'balance_after')
    op.add_column('support_tickets', sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('support_tickets', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('support_tickets', sa.Column('customer_satisfaction', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('support_tickets', sa.Column('ticket_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('support_tickets', sa.Column('sla_due_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('support_tickets', sa.Column('resolution_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('support_tickets', sa.Column('is_overdue', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('support_tickets', sa.Column('assigned_agent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('support_tickets', sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('support_tickets_assigned_agent_id_fkey', 'support_tickets', 'users', ['assigned_agent_id'], ['id'])
    op.drop_index(op.f('ix_support_tickets_category'), table_name='support_tickets')
    op.create_index('ix_support_tickets_user_id', 'support_tickets', ['user_id'], unique=False)
    op.create_index('ix_support_tickets_ticket_number', 'support_tickets', ['ticket_number'], unique=True)
    op.create_index('ix_support_tickets_status', 'support_tickets', ['status'], unique=False)
    op.create_index('ix_support_tickets_created_at', 'support_tickets', ['created_at'], unique=False)
    op.drop_column('support_tickets', 'assigned_to_id')
    op.add_column('stations', sa.Column('dealer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stations', type_='foreignkey')
    op.drop_constraint(None, 'stations', type_='foreignkey')
    op.create_foreign_key('stations_dealer_id_fkey', 'stations', 'dealer_profiles', ['dealer_id'], ['id'])
    op.drop_column('stations', 'total_slots')
    op.drop_column('stations', 'firmware_version')
    op.drop_column('stations', 'connectivity_type')
    op.drop_column('stations', 'power_type')
    op.drop_column('stations', 'station_type')
    op.drop_column('stations', 'vendor_id')
    op.drop_column('stations', 'zone_id')
    op.add_column('settlements', sa.Column('pdf_statement_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('settlements', sa.Column('total_commission', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('settlements', sa.Column('total_deductions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('settlements', sa.Column('net_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('settlements', sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('settlements', sa.Column('dealer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.create_foreign_key('settlements_dealer_id_fkey', 'settlements', 'dealer_profiles', ['dealer_id'], ['id'])
    op.drop_column('settlements', 'created_at')
    op.drop_column('settlements', 'transaction_reference')
    op.drop_column('settlements', 'currency')
    op.drop_column('settlements', 'payable_amount')
    op.drop_column('settlements', 'tax_amount')
    op.drop_column('settlements', 'platform_fee')
    op.drop_column('settlements', 'total_revenue')
    op.drop_column('settlements', 'vendor_id')
    op.add_column('route_stops', sa.Column('delivery_assignment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('route_stops_delivery_assignment_id_fkey', 'route_stops', 'delivery_assignments', ['delivery_assignment_id'], ['id'])
    op.add_column('delivery_routes', sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('delivery_routes_driver_id_fkey', 'delivery_routes', 'driver_profiles', ['driver_id'], ['id'])
    op.add_column('batteries', sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('batteries', sa.Column('voltage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('batteries', sa.Column('last_swap_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('batteries', sa.Column('capacity_ah', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('batteries', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'batteries', type_='foreignkey')
    op.drop_constraint(None, 'batteries', type_='foreignkey')
    op.drop_column('batteries', 'updated_at')
    op.drop_column('batteries', 'location_id')
    op.drop_column('batteries', 'location_type')
    op.drop_column('batteries', 'retirement_date')
    op.drop_column('batteries', 'batch_id')
    op.drop_column('batteries', 'spec_id')
    op.create_table('churnprediction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('churn_probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('churn_risk_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('days_since_last_activity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('days_since_last_rental', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_rentals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_spend', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('app_opens_last_30_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('searches_last_30_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('support_tickets_last_30_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('has_unresolved_issues', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('has_negative_reviews', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('payment_failures_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('top_churn_factors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('retention_action_taken', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('retention_action_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('did_churn', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('churn_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prediction_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='churnprediction_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='churnprediction_pkey')
    )
    op.create_index('ix_churnprediction_user_id', 'churnprediction', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('chat_sessions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assigned_agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_message_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('customer_satisfaction', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resolution_time_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], name='chat_sessions_assigned_agent_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_sessions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_index('ix_chat_sessions_status', 'chat_sessions', ['status'], unique=False)
    op.create_index('ix_chat_sessions_started_at', 'chat_sessions', ['started_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('attachment_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attachment_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='chat_messages_sender_id_fkey'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name='chat_messages_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_messages_pkey')
    )
    op.create_index('ix_chat_messages_timestamp', 'chat_messages', ['timestamp'], unique=False)
    op.create_index('ix_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_table('slots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('slot_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('battery_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['battery_id'], ['batteries.id'], name='slots_battery_id_fkey'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name='slots_station_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='slots_pkey')
    )
    op.create_table('demandforecast',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('forecast_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entity_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('forecast_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('forecast_hour', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('predicted_rentals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('predicted_swaps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('predicted_purchases', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confidence_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lower_bound', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('upper_bound', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actual_rentals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_swaps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_purchases', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('forecast_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model_features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='demandforecast_pkey')
    )
    op.create_index('ix_demandforecast_forecast_date', 'demandforecast', ['forecast_date'], unique=False)
    op.create_table('faq_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('helpful_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['faq_categories.id'], name='faq_items_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='faq_items_pkey')
    )
    op.create_index('ix_faq_items_question', 'faq_items', ['question'], unique=False)
    op.create_index('ix_faq_items_category_id', 'faq_items', ['category_id'], unique=False)
    op.create_table('driver_profiles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('driver_profiles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('license_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vehicle_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vehicle_plate', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('current_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_location_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_deliveries', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='driver_profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='driver_profiles_pkey'),
    sa.UniqueConstraint('user_id', name='driver_profiles_user_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('swap_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rental_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reserved_battery_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expiry_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], name='swap_requests_rental_id_fkey'),
    sa.ForeignKeyConstraint(['reserved_battery_id'], ['batteries.id'], name='swap_requests_reserved_battery_id_fkey'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name='swap_requests_station_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='swap_requests_pkey')
    )
    op.create_table('delivery_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('return_request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pickup_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('delivery_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('picked_up_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('proof_of_delivery_img', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_signature', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('otp_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.id'], name='delivery_assignments_driver_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['ecommerce_orders.id'], name='delivery_assignments_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='delivery_assignments_pkey')
    )
    op.create_table('swap_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rental_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_battery_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_battery_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('soc_in', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('soc_out', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('swap_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['new_battery_id'], ['batteries.id'], name='swap_histories_new_battery_id_fkey'),
    sa.ForeignKeyConstraint(['old_battery_id'], ['batteries.id'], name='swap_histories_old_battery_id_fkey'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], name='swap_histories_rental_id_fkey'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name='swap_histories_station_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='swap_histories_pkey')
    )
    op.create_table('adminuser',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='adminuser_pkey')
    )
    op.create_index('ix_adminuser_email', 'adminuser', ['email'], unique=True)
    op.create_table('auto_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('keywords', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('intent', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auto_responses_pkey')
    )
    op.create_table('faq_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='faq_categories_pkey'),
    sa.UniqueConstraint('name', name='faq_categories_name_key')
    )
    op.create_table('pricingrecommendation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recommendation_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recommended_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('price_change_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('demand_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('competition_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('seasonality_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('inventory_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('expected_revenue_change_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('expected_volume_change_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('risk_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('valid_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('valid_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('implemented_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('implemented_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_revenue_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('actual_volume_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['implemented_by'], ['users.id'], name='pricingrecommendation_implemented_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='pricingrecommendation_pkey')
    )
    op.drop_table('swap_sessions')
    op.drop_table('station_slots')
    op.drop_index(op.f('ix_vendor_documents_document_type'), table_name='vendor_documents')
    op.drop_table('vendor_documents')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_email'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_zones_name'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_telemetics_data_battery_id'), table_name='telemetics_data')
    op.drop_table('telemetics_data')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_table('cities')
    op.drop_table('battery_transfers')
    op.drop_index(op.f('ix_battery_lifecycle_events_event_type'), table_name='battery_lifecycle_events')
    op.drop_table('battery_lifecycle_events')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_table('regions')
    op.drop_table('dealer_settlements')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_battery_batches_batch_number'), table_name='battery_batches')
    op.drop_table('battery_batches')
    op.drop_index(op.f('ix_continents_name'), table_name='continents')
    op.drop_table('continents')
    op.drop_index(op.f('ix_battery_specs_name'), table_name='battery_specs')
    op.drop_table('battery_specs')
    # ### end Alembic commands ###
