"""upgrade_rbac_to_dynamic_hierarchy

Revision ID: c412c19683f6
Revises: d0ed96db3722
Create Date: 2026-02-04 17:15:02.869195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c412c19683f6'
down_revision: Union[str, None] = 'd0ed96db3722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('permissions', sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE permissions SET scope = 'global' WHERE scope IS NULL")
    op.alter_column('permissions', 'scope', nullable=False)
    
    op.add_column('permissions', sa.Column('constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    op.add_column('roles', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE roles SET category = 'system' WHERE category IS NULL")
    op.alter_column('roles', 'category', nullable=False)
    
    op.add_column('roles', sa.Column('level', sa.Integer(), nullable=True))
    op.execute("UPDATE roles SET level = 0 WHERE level IS NULL")
    op.alter_column('roles', 'level', nullable=False)
    
    op.add_column('roles', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles', 'roles', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'parent_id')
    op.drop_column('roles', 'level')
    op.drop_column('roles', 'category')
    op.drop_column('permissions', 'constraints')
    op.drop_column('permissions', 'scope')
    op.drop_column('permissions', 'resource_type')
    # ### end Alembic commands ###
