"""Add rating and rated_at to support tickets

Revision ID: c6b40bad8d46
Revises: b2c3d4e5f6g7
Create Date: 2026-04-08 13:17:42.408876

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c6b40bad8d46'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create Enum types first
    campaign_target_rule_type = sa.Enum('RENTAL_HISTORY', 'BIRTHDAY', 'LOCATION', 'LAST_ACTIVITY', 'SPENDING_TIER', name='campaigntargetruletype')
    campaign_type = sa.Enum('BIRTHDAY', 'SEASONAL', 'HISTORY_BASED', 'MANUAL', name='campaigntype')
    campaign_status = sa.Enum('DRAFT', 'SCHEDULED', 'ACTIVE', 'COMPLETED', 'PAUSED', name='campaignstatus')
    location_type_enum = sa.Enum('STATION', 'WAREHOUSE', 'SERVICE_CENTER', 'RECYCLING', name='locationtype')

    # Bind to connection and create types if they don't exist
    bind = op.get_bind()
    campaign_target_rule_type.create(bind, checkfirst=True)
    campaign_type.create(bind, checkfirst=True)
    campaign_status.create(bind, checkfirst=True)
    location_type_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign_targets', 'rule_type',
               existing_type=sa.VARCHAR(),
               type_=campaign_target_rule_type,
               existing_nullable=False,
               schema='core',
               postgresql_using='rule_type::campaigntargetruletype')
    op.alter_column('campaigns', 'type',
               existing_type=sa.VARCHAR(),
               type_=campaign_type,
               existing_nullable=False,
               schema='core',
               postgresql_using='type::campaigntype')
    
    # campaigns.status has a default that prevents automatic casting
    op.execute("ALTER TABLE core.campaigns ALTER COLUMN status DROP DEFAULT")
    op.alter_column('campaigns', 'status',
               existing_type=sa.VARCHAR(),
               type_=campaign_status,
               existing_nullable=False,
               schema='core',
               postgresql_using='status::campaignstatus')
    op.execute("ALTER TABLE core.campaigns ALTER COLUMN status SET DEFAULT 'DRAFT'::campaignstatus")

    op.alter_column('chat_messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='core')
    op.add_column('support_tickets', sa.Column('rating', sa.Integer(), nullable=True), schema='core')
    op.add_column('support_tickets', sa.Column('rated_at', sa.DateTime(), nullable=True), schema='core')
    
    # batteries.location_type has NULL values and a default issue
    op.execute("ALTER TABLE inventory.batteries ALTER COLUMN location_type DROP DEFAULT")
    
    # Backfill NULL values with 'WAREHOUSE' before setting NOT NULL
    op.execute("UPDATE inventory.batteries SET location_type = 'WAREHOUSE' WHERE location_type IS NULL")
    
    op.alter_column('batteries', 'location_type',
               existing_type=sa.VARCHAR(),
               type_=location_type_enum,
               nullable=False,
               schema='inventory',
               postgresql_using='location_type::locationtype')
    op.execute("ALTER TABLE inventory.batteries ALTER COLUMN location_type SET DEFAULT 'WAREHOUSE'::locationtype")

    op.drop_constraint('rfid_mappings_rfid_tag_key', 'rfid_mappings', schema='inventory', type_='unique')
    op.drop_index('ix_inventory_rfid_mappings_rfid_tag', table_name='rfid_mappings', schema='inventory')
    op.create_index(op.f('ix_inventory_rfid_mappings_rfid_tag'), 'rfid_mappings', ['rfid_tag'], unique=True, schema='inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_rfid_mappings_rfid_tag'), table_name='rfid_mappings', schema='inventory')
    op.create_index('ix_inventory_rfid_mappings_rfid_tag', 'rfid_mappings', ['rfid_tag'], unique=False, schema='inventory')
    op.create_unique_constraint('rfid_mappings_rfid_tag_key', 'rfid_mappings', ['rfid_tag'], schema='inventory')
    
    op.execute("ALTER TABLE inventory.batteries ALTER COLUMN location_type DROP DEFAULT")
    op.alter_column('batteries', 'location_type',
               existing_type=sa.Enum('STATION', 'WAREHOUSE', 'SERVICE_CENTER', 'RECYCLING', name='locationtype'),
               type_=sa.VARCHAR(),
               nullable=True,
               schema='inventory')
    
    op.drop_column('support_tickets', 'rated_at', schema='core')
    op.drop_column('support_tickets', 'rating', schema='core')
    op.alter_column('chat_messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='core')
    
    op.execute("ALTER TABLE core.campaigns ALTER COLUMN status DROP DEFAULT")
    op.alter_column('campaigns', 'status',
               existing_type=sa.Enum('DRAFT', 'SCHEDULED', 'ACTIVE', 'COMPLETED', 'PAUSED', name='campaignstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='core')
    op.execute("ALTER TABLE core.campaigns ALTER COLUMN status SET DEFAULT 'draft'")

    op.alter_column('campaigns', 'type',
               existing_type=sa.Enum('BIRTHDAY', 'SEASONAL', 'HISTORY_BASED', 'MANUAL', name='campaigntype'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='core')
    op.alter_column('campaign_targets', 'rule_type',
               existing_type=sa.Enum('RENTAL_HISTORY', 'BIRTHDAY', 'LOCATION', 'LAST_ACTIVITY', 'SPENDING_TIER', name='campaigntargetruletype'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='core')
    # ### end Alembic commands ###
