"""add_maintenance_tracking_fields

Revision ID: d0ed96db3722
Revises: 861e43cb106d
Create Date: 2026-02-04 17:09:21.494109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ed96db3722'
down_revision: Union[str, None] = '861e43cb106d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batteries', sa.Column('last_maintenance_date', sa.DateTime(), nullable=True))
    op.add_column('batteries', sa.Column('last_maintenance_cycles', sa.Integer(), nullable=False))
    op.add_column('stations', sa.Column('last_maintenance_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'last_maintenance_date')
    op.drop_column('batteries', 'last_maintenance_cycles')
    op.drop_column('batteries', 'last_maintenance_date')
    # ### end Alembic commands ###
