"""Add budget and tracking fields to dealer promotion

Revision ID: d7184b0c7f4d
Revises: 2c5038fb67d6
Create Date: 2026-03-04 00:43:16.267149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7184b0c7f4d'
down_revision: Union[str, None] = '2c5038fb67d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_history_user_id'), 'password_history', ['user_id'], unique=False)
    op.create_table('revenue_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('avg_transaction_value', sa.Float(), nullable=False),
    sa.Column('total_refunds', sa.Float(), nullable=False),
    sa.Column('net_revenue', sa.Float(), nullable=False),
    sa.Column('growth_percentage', sa.Float(), nullable=True),
    sa.Column('breakdown_by_dealer', sa.JSON(), nullable=True),
    sa.Column('breakdown_by_station', sa.JSON(), nullable=True),
    sa.Column('breakdown_by_category', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_reports_period_start'), 'revenue_reports', ['period_start'], unique=False)
    op.create_index(op.f('ix_revenue_reports_report_type'), 'revenue_reports', ['report_type'], unique=False)
    op.add_column('audit_logs', sa.Column('target_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('old_value', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('new_value', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.add_column('commission_configs', sa.Column('effective_from', sa.DateTime(), nullable=False))
    op.add_column('commission_configs', sa.Column('effective_until', sa.DateTime(), nullable=True))
    op.add_column('dealer_promotions', sa.Column('budget_limit', sa.Float(), nullable=True))
    op.add_column('dealer_promotions', sa.Column('daily_cap', sa.Integer(), nullable=True))
    op.add_column('dealer_promotions', sa.Column('total_discount_given', sa.Float(), nullable=False))
    op.add_column('dealer_promotions', sa.Column('impressions', sa.Integer(), nullable=False))
    op.add_column('dealer_promotions', sa.Column('applicable_station_ids', sa.String(), nullable=True))
    op.add_column('settlements', sa.Column('settlement_month', sa.String(), nullable=False))
    op.add_column('settlements', sa.Column('total_commission', sa.Float(), nullable=False))
    op.add_column('settlements', sa.Column('chargeback_amount', sa.Float(), nullable=False))
    op.add_column('settlements', sa.Column('net_payable', sa.Float(), nullable=False))
    op.add_column('settlements', sa.Column('payment_proof_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_settlements_settlement_month'), 'settlements', ['settlement_month'], unique=False)
    op.drop_column('settlements', 'payable_amount')
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'force_password_change')
    op.drop_column('users', 'password_changed_at')
    op.add_column('settlements', sa.Column('payable_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_settlements_settlement_month'), table_name='settlements')
    op.drop_column('settlements', 'payment_proof_url')
    op.drop_column('settlements', 'net_payable')
    op.drop_column('settlements', 'chargeback_amount')
    op.drop_column('settlements', 'total_commission')
    op.drop_column('settlements', 'settlement_month')
    op.drop_column('dealer_promotions', 'applicable_station_ids')
    op.drop_column('dealer_promotions', 'impressions')
    op.drop_column('dealer_promotions', 'total_discount_given')
    op.drop_column('dealer_promotions', 'daily_cap')
    op.drop_column('dealer_promotions', 'budget_limit')
    op.drop_column('commission_configs', 'effective_until')
    op.drop_column('commission_configs', 'effective_from')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'new_value')
    op.drop_column('audit_logs', 'old_value')
    op.drop_column('audit_logs', 'target_id')
    op.drop_index(op.f('ix_revenue_reports_report_type'), table_name='revenue_reports')
    op.drop_index(op.f('ix_revenue_reports_period_start'), table_name='revenue_reports')
    op.drop_table('revenue_reports')
    op.drop_index(op.f('ix_password_history_user_id'), table_name='password_history')
    op.drop_table('password_history')
    # ### end Alembic commands ###
