"""schema_consolidation

Revision ID: eb06e42014cb
Revises: 
Create Date: 2026-03-30 11:57:35.595756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb06e42014cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_biometric_tokens_device_id', table_name='biometric_tokens')
    op.drop_index('ix_biometric_tokens_user_id', table_name='biometric_tokens')
    op.drop_table('biometric_tokens')
    op.drop_table('maintenanceschedule')
    op.drop_table('blogs')
    op.drop_index('ix_demandforecast_forecast_date', table_name='demandforecast')
    op.drop_table('demandforecast')
    op.drop_table('inventory_audit_logs')
    op.drop_table('pricingrecommendation')
    op.drop_table('stationdowntime')
    op.drop_index('ix_churnprediction_user_id', table_name='churnprediction')
    op.drop_table('churnprediction')
    op.drop_table('favorite')
    op.drop_index('ix_telemetics_data_battery_id', table_name='telemetics_data')
    op.drop_table('telemetics_data')
    op.drop_table('notificationpreference')
    op.drop_table('maintenancerecord')
    op.drop_table('notification')
    op.drop_index('ix_translation_key', table_name='translation')
    op.drop_index('ix_translation_language_code', table_name='translation')
    op.drop_table('translation')
    op.drop_table('rentalevent')
    op.drop_table('faq')
    op.drop_index('ix_battery_specs_name', table_name='battery_specs')
    op.drop_table('battery_specs')
    op.drop_index('ix_system_configs_key', table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index('ix_feature_flags_name', table_name='feature_flags')
    op.drop_table('feature_flags')
    op.add_column('banners', sa.Column('deep_link', sa.String(), nullable=True))
    op.add_column('banners', sa.Column('external_url', sa.String(), nullable=True))
    op.add_column('banners', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('banners', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('banners', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('banners', sa.Column('click_count', sa.Integer(), nullable=False))
    op.add_column('banners', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('banners', 'target_url')
    op.create_foreign_key(None, 'chargebacks', 'settlements', ['settlement_id'], ['id'])
    op.create_foreign_key(None, 'late_fees', 'invoices', ['invoice_id'], ['id'])
    op.add_column('legal_documents', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('legal_documents', sa.Column('force_update', sa.Boolean(), nullable=False))
    op.add_column('legal_documents', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('legal_documents', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_legal_documents_slug'), 'legal_documents', ['slug'], unique=True)
    op.drop_column('legal_documents', 'type')
    op.create_foreign_key(None, 'refunds', 'transactions', ['transaction_id'], ['id'])
    op.drop_column('users', 'sessions')
    op.drop_column('users', 'email_verification_sent_at')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'two_factor_auth')
    op.drop_column('users', 'tenant_id')
    op.drop_column('users', 'email_verification_token')
    op.create_foreign_key(None, 'wallet_withdrawal_requests', 'wallets', ['wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet_withdrawal_requests', type_='foreignkey')
    op.add_column('users', sa.Column('email_verification_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tenant_id', sa.VARCHAR(), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('two_factor_auth', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email_verification_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('sessions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'refunds', type_='foreignkey')
    op.add_column('legal_documents', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_legal_documents_slug'), table_name='legal_documents')
    op.drop_column('legal_documents', 'updated_at')
    op.drop_column('legal_documents', 'published_at')
    op.drop_column('legal_documents', 'force_update')
    op.drop_column('legal_documents', 'slug')
    op.drop_constraint(None, 'late_fees', type_='foreignkey')
    op.drop_constraint(None, 'chargebacks', type_='foreignkey')
    op.add_column('banners', sa.Column('target_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('banners', 'updated_at')
    op.drop_column('banners', 'click_count')
    op.drop_column('banners', 'end_date')
    op.drop_column('banners', 'start_date')
    op.drop_column('banners', 'priority')
    op.drop_column('banners', 'external_url')
    op.drop_column('banners', 'deep_link')
    op.create_table('feature_flags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('rollout_percentage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enabled_for_users', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('enabled_for_tenants', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='feature_flags_pkey')
    )
    op.create_index('ix_feature_flags_name', 'feature_flags', ['name'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_configs_pkey')
    )
    op.create_index('ix_system_configs_key', 'system_configs', ['key'], unique=False)
    op.create_table('battery_specs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('voltage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('capacity_ah', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dimensions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cycle_life_expectancy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='battery_specs_pkey')
    )
    op.create_index('ix_battery_specs_name', 'battery_specs', ['name'], unique=False)
    op.create_table('faq',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='faq_pkey')
    )
    op.create_table('rentalevent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rental_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('battery_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['battery_id'], ['batteries.id'], name='rentalevent_battery_id_fkey'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], name='rentalevent_rental_id_fkey'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name='rentalevent_station_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rentalevent_pkey')
    )
    op.create_table('translation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('language_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('context', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='translation_pkey')
    )
    op.create_index('ix_translation_language_code', 'translation', ['language_code'], unique=False)
    op.create_index('ix_translation_key', 'translation', ['key'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notification_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notification_pkey')
    )
    op.create_table('maintenancerecord',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('technician_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('maintenance_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('parts_replaced', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('performed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name='maintenancerecord_technician_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='maintenancerecord_pkey')
    )
    op.create_table('notificationpreference',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notifications_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('push_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('email_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sms_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('whatsapp_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('transactional_push', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('transactional_email', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('transactional_sms', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('promotional_push', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('promotional_email', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('promotional_sms', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('battery_alerts_push', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('battery_alerts_email', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('battery_alerts_sms', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('rental_reminders_push', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('rental_reminders_email', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('rental_reminders_sms', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('payment_push', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('payment_email', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('payment_sms', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('swap_suggestions_push', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('swap_suggestions_email', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('maintenance_push', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('maintenance_email', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('marketing_push', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('marketing_email', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('marketing_sms', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('max_push_per_day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_email_per_day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_sms_per_day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quiet_hours_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('quiet_hours_start', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('quiet_hours_end', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('preferred_language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notificationpreference_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notificationpreference_pkey'),
    sa.UniqueConstraint('user_id', name='notificationpreference_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('telemetics_data',
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('battery_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('voltage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('current', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('soc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('soh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gps_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gps_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gps_altitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gps_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_codes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['battery_id'], ['batteries.id'], name='telemetics_data_battery_id_fkey'),
    sa.PrimaryKeyConstraint('timestamp', 'battery_id', name='telemetics_data_pkey')
    )
    op.create_index('ix_telemetics_data_battery_id', 'telemetics_data', ['battery_id'], unique=False)
    op.create_table('favorite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name='favorite_station_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorite_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_pkey')
    )
    op.create_table('churnprediction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('churn_probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('churn_risk_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('days_since_last_activity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('days_since_last_rental', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_rentals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_spend', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('app_opens_last_30_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('searches_last_30_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('support_tickets_last_30_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('has_unresolved_issues', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('has_negative_reviews', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('payment_failures_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('top_churn_factors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('retention_action_taken', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('retention_action_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('did_churn', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('churn_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prediction_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='churnprediction_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='churnprediction_pkey')
    )
    op.create_index('ix_churnprediction_user_id', 'churnprediction', ['user_id'], unique=False)
    op.create_table('stationdowntime',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name='stationdowntime_station_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stationdowntime_pkey')
    )
    op.create_table('pricingrecommendation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recommendation_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recommended_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('price_change_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('demand_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('competition_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('seasonality_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('inventory_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('expected_revenue_change_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('expected_volume_change_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('risk_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('valid_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('valid_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('implemented_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('implemented_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_revenue_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('actual_volume_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['implemented_by'], ['users.id'], name='pricingrecommendation_implemented_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='pricingrecommendation_pkey')
    )
    op.create_table('inventory_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('battery_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('from_location_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('from_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_location_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('to_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='inventory_audit_logs_pkey')
    )
    op.create_table('demandforecast',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('forecast_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entity_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('forecast_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('forecast_hour', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('predicted_rentals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('predicted_swaps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('predicted_purchases', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confidence_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lower_bound', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('upper_bound', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actual_rentals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_swaps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_purchases', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('forecast_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model_features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='demandforecast_pkey')
    )
    op.create_index('ix_demandforecast_forecast_date', 'demandforecast', ['forecast_date'], unique=False)
    op.create_table('blogs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='blogs_pkey')
    )
    op.create_table('maintenanceschedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interval_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interval_cycles', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_maintenance_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_maintenance_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('checklist', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='maintenanceschedule_pkey')
    )
    op.create_table('biometric_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('biometric_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('public_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('device_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device_model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('os_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='biometric_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='biometric_tokens_pkey')
    )
    op.create_index('ix_biometric_tokens_user_id', 'biometric_tokens', ['user_id'], unique=False)
    op.create_index('ix_biometric_tokens_device_id', 'biometric_tokens', ['device_id'], unique=False)
    # ### end Alembic commands ###
