"""sync_remaining_schema

Revision ID: eef1b0eaa6ef
Revises: 30689346f8dc
Create Date: 2026-02-11 17:22:21.526925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eef1b0eaa6ef'
down_revision: Union[str, None] = '30689346f8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('menu_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_name'), 'menus', ['name'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('logo_width', sa.Integer(), nullable=True),
    sa.Column('logo_height', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_code'), 'organizations', ['code'], unique=True)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('organization_social_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('website', 'facebook', 'instagram', 'linkedin', 'twitter', 'youtube', 'others', name='socialplatform'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_rights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'menu_id', name='unique_role_menu')
    )
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('pincode', sa.String(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_code'), 'branches', ['code'], unique=True)
    op.create_index(op.f('ix_branches_name'), 'branches', ['name'], unique=False)
    op.create_table('user_access_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('path_pattern', sa.String(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_access_paths_path_pattern'), 'user_access_paths', ['path_pattern'], unique=False)
    op.create_index(op.f('ix_user_access_paths_user_id'), 'user_access_paths', ['user_id'], unique=False)
    op.create_table('dealer_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_documents_document_type'), 'dealer_documents', ['document_type'], unique=False)
    op.add_column('commission_logs', sa.Column('settlement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'commission_logs', 'settlements', ['settlement_id'], ['id'])
    op.add_column('dealer_profiles', sa.Column('bank_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('kyc_documents', sa.Column('metadata', sa.String(), nullable=True))
    op.add_column('maintenanceschedule', sa.Column('last_maintenance_date', sa.DateTime(), nullable=True))
    op.add_column('maintenanceschedule', sa.Column('next_maintenance_date', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('parent_role_id', sa.Integer(), nullable=True))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_constraint('roles_parent_id_fkey', 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'roles', ['parent_role_id'], ['id'])
    op.drop_column('roles', 'parent_id')
    op.add_column('settlements', sa.Column('dealer_id', sa.Integer(), nullable=True))
    op.alter_column('settlements', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'settlements', 'users', ['dealer_id'], ['id'])
    op.create_index(op.f('ix_stations_latitude'), 'stations', ['latitude'], unique=False)
    op.create_index(op.f('ix_stations_longitude'), 'stations', ['longitude'], unique=False)
    op.add_column('user_roles', sa.Column('assigned_by', sa.Integer(), nullable=True))
    op.add_column('user_roles', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('user_roles', sa.Column('effective_from', sa.DateTime(), nullable=False))
    op.add_column('user_roles', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('user_roles', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'user_roles', 'admin_users', ['assigned_by'], ['id'])
    op.add_column('users', sa.Column('status', sa.String(), nullable=False))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('kyc_rejection_reason', sa.String(), nullable=True))
    op.add_column('users', sa.Column('two_factor_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('two_factor_backup_codes', sa.String(), nullable=True))
    op.add_column('users', sa.Column('two_factor_enabled_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('two_factor_pending', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verification_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verification_sent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_email_verification_token'), 'users', ['email_verification_token'], unique=False)
    op.create_index(op.f('ix_users_last_login'), 'users', ['last_login'], unique=False)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.add_column('video_kyc_sessions', sa.Column('agent_notes', sa.String(), nullable=True))
    op.add_column('warehouses', sa.Column('code', sa.String(), nullable=False))
    op.add_column('warehouses', sa.Column('pincode', sa.String(), nullable=False))
    op.add_column('warehouses', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('warehouses', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('warehouses', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('warehouses', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_foreign_key(None, 'warehouses', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.alter_column('warehouses', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('warehouses', 'updated_at')
    op.drop_column('warehouses', 'created_at')
    op.drop_column('warehouses', 'branch_id')
    op.drop_column('warehouses', 'pincode')
    op.drop_column('warehouses', 'code')
    op.drop_column('video_kyc_sessions', 'agent_notes')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_last_login'), table_name='users')
    op.drop_index(op.f('ix_users_email_verification_token'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'email_verification_sent_at')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'two_factor_pending')
    op.drop_column('users', 'two_factor_enabled_at')
    op.drop_column('users', 'two_factor_backup_codes')
    op.drop_column('users', 'two_factor_secret')
    op.drop_column('users', 'kyc_rejection_reason')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'status')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_column('user_roles', 'created_at')
    op.drop_column('user_roles', 'expires_at')
    op.drop_column('user_roles', 'effective_from')
    op.drop_column('user_roles', 'notes')
    op.drop_column('user_roles', 'assigned_by')
    op.drop_index(op.f('ix_stations_longitude'), table_name='stations')
    op.drop_index(op.f('ix_stations_latitude'), table_name='stations')
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.alter_column('settlements', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('settlements', 'dealer_id')
    op.add_column('roles', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key('roles_parent_id_fkey', 'roles', 'roles', ['parent_id'], ['id'])
    op.drop_column('roles', 'is_active')
    op.drop_column('roles', 'parent_role_id')
    op.drop_column('maintenanceschedule', 'next_maintenance_date')
    op.drop_column('maintenanceschedule', 'last_maintenance_date')
    op.drop_column('kyc_documents', 'metadata')
    op.drop_column('dealer_profiles', 'bank_details')
    op.drop_constraint(None, 'commission_logs', type_='foreignkey')
    op.drop_column('commission_logs', 'settlement_id')
    op.drop_index(op.f('ix_dealer_documents_document_type'), table_name='dealer_documents')
    op.drop_table('dealer_documents')
    op.drop_index(op.f('ix_user_access_paths_user_id'), table_name='user_access_paths')
    op.drop_index(op.f('ix_user_access_paths_path_pattern'), table_name='user_access_paths')
    op.drop_table('user_access_paths')
    op.drop_index(op.f('ix_branches_name'), table_name='branches')
    op.drop_index(op.f('ix_branches_code'), table_name='branches')
    op.drop_table('branches')
    op.drop_table('role_rights')
    op.drop_table('organization_social_links')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_code'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_menus_name'), table_name='menus')
    op.drop_table('menus')
    # ### end Alembic commands ###
