"""add_multi_tenancy_and_feature_flags

Revision ID: ef3c2dc85e46
Revises: c412c19683f6
Create Date: 2026-02-04 17:16:57.702843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ef3c2dc85e46'
down_revision: Union[str, None] = 'c412c19683f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batteries', sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_batteries_tenant_id'), 'batteries', ['tenant_id'], unique=False)
    op.add_column('stations', sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_stations_tenant_id'), 'stations', ['tenant_id'], unique=False)
    op.add_column('users', sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    op.drop_index(op.f('ix_stations_tenant_id'), table_name='stations')
    op.drop_column('stations', 'tenant_id')
    op.drop_index(op.f('ix_batteries_tenant_id'), table_name='batteries')
    op.drop_column('batteries', 'tenant_id')
    # ### end Alembic commands ###
