"""station_schema_fixes

Revision ID: ff5a7d699e68
Revises: 3e3d655d355d
Create Date: 2026-03-24 09:40:20.546060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5a7d699e68'
down_revision: Union[str, None] = '3e3d655d355d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('troubleshooting_steps', sa.String(), nullable=True))
    op.alter_column('settlements', 'dealer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_settlements_dealer_id'), 'settlements', ['dealer_id'], unique=False)
    op.drop_constraint('settlements_dealer_id_fkey', 'settlements', type_='foreignkey')
    op.create_foreign_key('fk_settlements_dealer_id', 'settlements', 'dealer_profiles', ['dealer_id'], ['id'])
    op.add_column('stations', sa.Column('charger_configs', sa.String(), nullable=True))
    op.add_column('stations', sa.Column('operating_temp_min', sa.Float(), nullable=True))
    op.add_column('stations', sa.Column('operating_temp_max', sa.Float(), nullable=True))
    op.add_column('stations', sa.Column('auto_close_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('stations', sa.Column('auto_close_grace_minutes', sa.Integer(), nullable=False, server_default=sa.text('30')))
    op.add_column('stations', sa.Column('structured_hours', sa.String(), nullable=True))
    op.add_column('stations', sa.Column('geofence_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_stations_geofence_id', 'stations', 'geofence', ['geofence_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_stations_geofence_id', 'stations', type_='foreignkey')
    op.drop_column('stations', 'geofence_id')
    op.drop_column('stations', 'structured_hours')
    op.drop_column('stations', 'auto_close_grace_minutes')
    op.drop_column('stations', 'auto_close_enabled')
    op.drop_column('stations', 'operating_temp_max')
    op.drop_column('stations', 'operating_temp_min')
    op.drop_column('stations', 'charger_configs')
    op.drop_constraint('fk_settlements_dealer_id', 'settlements', type_='foreignkey')
    op.create_foreign_key('settlements_dealer_id_fkey', 'settlements', 'users', ['dealer_id'], ['id'])
    op.drop_index(op.f('ix_settlements_dealer_id'), table_name='settlements')
    op.alter_column('settlements', 'dealer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('alerts', 'troubleshooting_steps')
    # ### end Alembic commands ###
