"""add_audit_logs

Revision ID: f1778d4ea16f
Revises: e52025de5b28
Create Date: 2025-12-22 14:41:34.063429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f1778d4ea16f'
down_revision: Union[str, None] = 'e52025de5b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlog_action'), 'auditlog', ['action'], unique=False)
    op.create_index(op.f('ix_auditlog_user_id'), 'auditlog', ['user_id'], unique=False)
    # op.create_table('securityevent',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    # sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    # sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    # sa.Column('source_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.Column('timestamp', sa.DateTime(), nullable=False),
    # sa.Column('is_resolved', sa.Boolean(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_securityevent_event_type'), 'securityevent', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_securityevent_event_type'), table_name='securityevent')
    # op.drop_table('securityevent')
    op.drop_index(op.f('ix_auditlog_user_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_action'), table_name='auditlog')
    op.drop_table('auditlog')
    # ### end Alembic commands ###
